/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for finding unused files */
export interface UnusedFilesOptions {
  /** Entry point files or glob patterns */
  entry: Array<string>
  /** Project files to check (glob patterns) */
  project?: Array<string>
  /** Working directory (defaults to current directory) */
  cwd?: string
  /** Patterns to ignore */
  ignore?: Array<string>
  /** Include files from node_modules (default: false) */
  includeNodeModules?: boolean
}
/** Report of unused files analysis */
export interface UnusedFilesReport {
  /** List of unused file paths (relative to cwd) */
  unusedFiles: Array<string>
  /** Total number of project files analyzed */
  totalFiles: number
  /** Number of unused files found */
  unusedCount: number
}
/**
 * Find unused files in a JavaScript/TypeScript project (async)
 *
 * @param options - Configuration options
 * @returns Promise with report containing unused files and statistics
 */
export declare function findUnused(options: UnusedFilesOptions): Promise<UnusedFilesReport>
/**
 * Find unused files in a JavaScript/TypeScript project (sync)
 *
 * @param options - Configuration options
 * @returns Report containing unused files and statistics
 */
export declare function findUnusedSync(options: UnusedFilesOptions): UnusedFilesReport
/**
 * Find all files reachable from entry points (async)
 *
 * @param options - Configuration options
 * @returns Promise with array of reachable file paths
 */
export declare function findReachable(options: UnusedFilesOptions): Promise<Array<string>>
